import AffineGaussianInvariant.InvariantTheory.MixedTensor.Basic
import AffineGaussianInvariant.InvariantTheory.MixedTensor.PairingFunctionals
import AffineGaussianInvariant.InvariantTheory.MixedTensor.FFTContract
