import AffineGaussianInvariant.InvariantTheory.MixedTensor.FFTContractV2

set_option autoImplicit false

namespace AffineGaussianInvariant.InvariantTheory.MixedTensor

/--
Concrete complex mixed-tensor target used in the complexified proof of Claim S6.3.
For block dimension `r` and balanced degree `p`, it asserts that every separately
multilinear `GL(r,ℂ)`-invariant functional is generated by complete contractions.
-/
def ConcreteS6_3 (r p : ℕ) : Prop :=
  FFTStatement ℂ (Fin r → ℂ) p

/-- The concrete target unfolds exactly to the reusable FFT contract. -/
theorem concreteS6_3_iff (r p : ℕ) :
    ConcreteS6_3 r p ↔ FFTStatement ℂ (Fin r → ℂ) p :=
  Iff.rfl

end AffineGaussianInvariant.InvariantTheory.MixedTensor
